# DefectDojo - Docker Compose
# Execute: docker-compose up -d

version: '3.8'

services:
  nginx:
    image: defectdojo/defectdojo-nginx:latest
    depends_on:
      - uwsgi
    ports:
      - "8080:8080"
    environment:
      NGINX_METRICS_ENABLED: "false"
    volumes:
      - defectdojo_media:/usr/share/nginx/html/media

  uwsgi:
    image: defectdojo/defectdojo-django:latest
    depends_on:
      - postgres
      - redis
    entrypoint: ['/wait-for-it.sh', 'postgres:5432', '-t', '30', '--', '/entrypoint-uwsgi.sh']
    environment:
      DD_DEBUG: 'False'
      DD_DJANGO_METRICS_ENABLED: 'False'
      DD_ALLOWED_HOSTS: '*'
      DD_DATABASE_URL: 'postgresql://defectdojo:defectdojo@postgres:5432/defectdojo'
      DD_SECRET_KEY: 'change-me-in-production'
      DD_CREDENTIAL_AES_256_KEY: 'change-me-32-chars-minimum-key!'
      DD_CELERY_BROKER_URL: 'redis://redis:6379/0'
      DD_CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
    volumes:
      - defectdojo_media:/app/media

  celerybeat:
    image: defectdojo/defectdojo-django:latest
    depends_on:
      - postgres
      - redis
    entrypoint: ['/wait-for-it.sh', 'postgres:5432', '-t', '30', '--', '/entrypoint-celery-beat.sh']
    environment:
      DD_DATABASE_URL: 'postgresql://defectdojo:defectdojo@postgres:5432/defectdojo'
      DD_SECRET_KEY: 'change-me-in-production'
      DD_CREDENTIAL_AES_256_KEY: 'change-me-32-chars-minimum-key!'
      DD_CELERY_BROKER_URL: 'redis://redis:6379/0'
      DD_CELERY_RESULT_BACKEND: 'redis://redis:6379/0'

  celeryworker:
    image: defectdojo/defectdojo-django:latest
    depends_on:
      - postgres
      - redis
    entrypoint: ['/wait-for-it.sh', 'postgres:5432', '-t', '30', '--', '/entrypoint-celery-worker.sh']
    environment:
      DD_DATABASE_URL: 'postgresql://defectdojo:defectdojo@postgres:5432/defectdojo'
      DD_SECRET_KEY: 'change-me-in-production'
      DD_CREDENTIAL_AES_256_KEY: 'change-me-32-chars-minimum-key!'
      DD_CELERY_BROKER_URL: 'redis://redis:6379/0'
      DD_CELERY_RESULT_BACKEND: 'redis://redis:6379/0'

  initializer:
    image: defectdojo/defectdojo-django:latest
    depends_on:
      - postgres
    entrypoint: ['/wait-for-it.sh', 'postgres:5432', '-t', '30', '--', '/entrypoint-initializer.sh']
    environment:
      DD_DATABASE_URL: 'postgresql://defectdojo:defectdojo@postgres:5432/defectdojo'
      DD_SECRET_KEY: 'change-me-in-production'
      DD_CREDENTIAL_AES_256_KEY: 'change-me-32-chars-minimum-key!'
      DD_ADMIN_USER: 'admin'
      DD_ADMIN_PASSWORD: 'admin123'
      DD_ADMIN_MAIL: 'admin@defectdojo.local'

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: defectdojo
      POSTGRES_USER: defectdojo
      POSTGRES_PASSWORD: defectdojo
    volumes:
      - defectdojo_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  defectdojo_media:
  defectdojo_postgres:
